#!/bin/bash
# Shadock move your podcast mp3 from iTunes in your périphéric

# function
shadock_rm () {
	echo "Début de la suppression"
	rm -fr $shadock_dir/*
	echo "Fin de la supression"
}

shadock_cp () {
	echo "Début de la copie"
	SAVEIFS=$IFS
	IFS=$(echo -en "\n\b")
	FILES=$HOME/Music/iTunes/"iTunes Media"/Podcasts/*
	count_all=$(find $FILES -name '*.mp3' | wc -l );
	count_progress="0";

	for f in $FILES
	do
	 	count=$(find $f -type f -name '*.mp3' | wc -l)

	 	if [ $count -gt 0 ];
		then
	 		echo "$count_progress/$count_all";
	 		count_progress=$(echo "$count_progress+$count" | bc -l );
	 		basename $f;
	 		cp -r $f $shadock_dir/$f_last;
	 	fi
	done
	# restore $IFS
	IFS=$SAVEIFS
	echo "$count_all/$count_all"
	echo "Fin de la copie"
}

# init $shadock_dir
case $1 in
	"test")
		echo "Ceci est un test"
		shadock_dir=$HOME/test
		;;
	"walkman")
		echo "Walkam start"
		shadock_dir=/Volumes/WALKMAN/MUSIC/podcast_shadock
		;;
esac

# action
case $2 in
	"rm")
		shadock_rm
		;;
	"cp")
		shadock_cp
		;;
	*)
		shadock_rm
		shadock_cp
		;;
esac
