#!/bin/bash
# Shadock move your podcast mp3 from iTunes in your périphéric

# function
shadock_rm () {
	rm $shadock_dir/*
}

shadock_cp () {
	find $HOME/Music/iTunes/"iTunes Media"/Podcasts/ -name "*.mp3" -exec cp '{}' $shadock_dir/ \;
}

# init $shadock_dir
case $1 in
	"test")
		echo "Ceci est un test"
		shadock_dir=$HOME/test
		;;
	"walkman")
		echo "Walkam start"
		shadock_dir=/Volumes/WALKMAN/MUSIC/podcast_shadock
		;;
esac

# action
case $2 in
	"rm")
		shadock_rm
		;;
	"cp")
		shadock_cp
		;;
	*)
		shadock_rm
		shadock_cp
		;;
esac
