#!/bin/bash
# Shadock move your podcast mp3 from iTunes in your périphéric

# function
shadock_rm () {
	rm -r $shadock_dir/*
}

shadock_cp () {
	SAVEIFS=$IFS
	IFS=$(echo -en "\n\b")
	FILES=$HOME/Music/iTunes/"iTunes Media"/Podcasts/*
	for f in $FILES
	do
		count=$(find $f -type f -name '*.mp3' | wc -l)

		if [ $count -gt 0 ]; then
		 	basename $f
			cp -r $f $shadock_dir/$f_last
		fi
	done
	# restore $IFS
	IFS=$SAVEIFS
}

# init $shadock_dir
case $1 in
	"test")
		echo "Ceci est un test"
		shadock_dir=$HOME/test
		;;
	"walkman")
		echo "Walkam start"
		shadock_dir=/Volumes/WALKMAN/MUSIC/podcast_shadock
		;;
esac

# action
case $2 in
	"rm")
		shadock_rm
		;;
	"cp")
		shadock_cp
		;;
	*)
		shadock_rm
		shadock_cp
		;;
esac
